#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url:
#    username:
#    password:
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  jwt:
#    key:
#    access-token-expiration-minutes:
#    refresh-token-expiration-minutes:
#  mail:
#    host: smtp.gmail.com
#    port: 465
#    username:
#    password:
#    properties:
#      mail.smtp.auth: true
#      mail.smtp.ssl.enable: true
#      mail.smtp.ssl.trust: smtp.gmail.com
#  redis:
#    host:
#    port:
#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
#    tagsSorter: alpha
#    operations-sorter: method
#    display-request-duration: true